version: '2'
services:
  twistributer:
    image: twistributer
    command: /app/twistributer
    volumes:
      - ./setting.yml:/app/setting.yml
    expose:
      - 3000
    ports:
      - "3080:3000"
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: twistributer,logger=info
