version: '2'
services:
  twistributer:
    image: flum1025/twistributer
    volumes:
      - ./setting.yml:/app/setting.yml
    ports:
      - "3000:3000"
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: twistributer,logger=info
