[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.lint]
command = "cargo"
args = ["clippy"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
dependencies = [
  "clean",
  "lint"
]
